### ISSUE TITLE
Rossum skill times out

### ISSUE THREAD

**Issue by cbetta** [box-community/sample-document-skills#5]
@PhilMayer hey currently the Skill seems to time out for me, as the API gateway only supports 30 seconds. We could up the skill timeout to 900 seconds (max supported by AWS) but wondering if there's a different way to do this.

**Comment by PhilMayer** [comment]
@cbetta I did find that in some cases Rossum needed almost two minutes to be allowed to do its thing. 900 seems like a bit overkill, but anything over 120 seconds will be technically peachy.

**Comment by cbetta** [comment]
Ok, I'll update it to 120s. In general the way around this is to split the skill into 2 endpoints, and provide a callback URL to the ML API. I assume Rossum doesn't support this?

**Comment by PhilMayer** [comment]
That's right, from what I can tell. From their dev docs: 

> Users are expected to periodically check documents status until they leave the processing phase. Minimum interval between document status queries should be at least 500ms.

**Comment by cbetta** [comment]
Cool, then we can leave this as-is

**Comment by pasky** [comment]
(Since this appears in google searches - note that a better option is to rely on our Document Management API, which allows for callbacks, as well as offering a user interface for the capture etc. At Rossum, we hope to contribute a switch-over from the currently implemented DE API to the DM API to the Box skill in the future.)

**Comment by cbetta** [comment]
@pasky hi, that's great to hear! I'd love to get this skill updated with this new API. Any help I can provide, please let me know.
